grails-app/domain/preciosdinamicos/Purchase.groovy
package preciosdinamicos

import javax.transaction.Transactional

enum PurchaseStatus {
    PENDING,
    DONE
}

class Purchase {

    User user
    List<PurchaseItem> products
    Date date
    Money amount
    PurchaseStatus status

    static constraints = {
        
    }
    static mapping = {
        products cascade: 'all'
    }
    static embedded = ['amount']

    Purchase(User user, List<Product> products) {
        this.user = user
        float totalAmount = products?.sum { p -> p.calculateDinamicPrice(user) }
        this.amount = new Money(totalAmount, "ARS")
        this.products = new ArrayList<>()
        products.each {e -> this.products.add(new PurchaseItem(e.id,e.name,e.price,e.description))}
        this.date = new Date()
        status = PurchaseStatus.PENDING
    }

    def pay() {
        if (this.status == PurchaseStatus.PENDING) {
            this.status = PurchaseStatus.DONE
            Payment payment = new Payment(this, "VISA", this.amount)
            payment.save()
        } else {
            throw IllegalAccessException("No se puede pagar una compra ya pagada")
        }
    }

    def isPending() {
        PurchaseStatus.PENDING == this.status
    }

    def static removeInvalidPurchases(User user) {
        List<Purchase> purchases = findAllByUser(user)
        List<Purchase> purchasesToRemove = purchases.findAll { p -> p.date < new Date() - 15}
        removePurchases(purchasesToRemove)
    }

    @Transactional
    private static void removePurchases(List<Purchase> purchases) {
        purchases.each {
            p ->
                p.products.each {
                    prod ->
                        def product = Product.findById(prod.code)
                        product.stock++
                        product.save()
                }
        }
        purchases*.delete()
    }
}

grails-app/controllers/preciosdinamicos/PurchaseController.groovy
package preciosdinamicos

class PurchaseController {
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 20, 100)
        def user = getUserFromSession()
        List<Purchase> purchases = Purchase.findAllByUser(user)
        respond purchases, model: [purchaseCount: purchases.size(), max: params.max]
    }

    def show(Purchase purchase) {
        def user = User.findById(session.getAttribute("user"))
        respond purchase, model: [user: user]
    }

    def pay(Purchase purchase) {
        def user = User.findById(session.getAttribute("user"))
        respond purchase, model: [user: user]
    }

    def validatePay(Purchase purchase) {
        try {
            purchase.pay()
            flash.message = "Felicitaciones por su compra!"
            flash.class = "alert alert-success"
        } catch (IllegalAccessException ex) {
            flash.message = "Esta compra ya está pagada."
            flash.class = "alert alert-danger"
        }

        redirect(controller: 'purchase', action: 'show', id: purchase.getId())
    }


    def removeInvalidPurchases() {
        def user = getUserFromSession()
        Purchase.removeInvalidPurchases(user)
        flash.message = "Se han removido las compras inválidas"
        redirect(controller: 'purchase', action: 'index')
    }

    private User getUserFromSession() {
        def userId = session.getAttribute("user")
        User user = User.findById(userId)
        user
    }
}

grails-app/views/purchase/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'purchase.label', default: 'Purchase')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#create-purchase" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-purchase" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.purchase}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.purchase}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="purchase"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/purchase/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'purchase.label', default: 'Purchase')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-purchase" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-purchase" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.purchase}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.purchase}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.purchase}" method="PUT">
                <g:hiddenField name="version" value="${this.purchase?.version}" />
                <fieldset class="form">
                    <f:all bean="purchase"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/purchase/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'purchase.label', default: 'Purchase')}" />
        <title>Compras</title>
    </head>
    <body>
        <a href="#list-purchase" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-purchase" class="content scaffold-list" role="main">
            <h1>Compras</h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>

            <table class='display'>
                <tr>
                    <th><g:message code="purchase.date"/></th>
                    <th><g:message code="purchase.amount"/></th>
                    <th><g:message code="purchase.products"/></th>
                    <th></th>
                </tr>
                <g:each in="${purchaseList}" var="purchase">
                    <tr>
                        <td>${purchase.date}</td>
                        <td>${purchase.amount}</td>
                        <td>${purchase.products*.name.join(",")}</td>
                    </tr>
                </g:each>
            </table>
            <g:form  controller="PurchaseController" >
                <fieldset class="buttons">
                    <g:link class="delete" action="removeInvalidPurchases"><g:message code="default.button.purchase.clear.label"
                                                                     default="clear"/></g:link>
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/purchase/pay.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'purchase', default: 'Purchase')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
    <div id="page">

        <g:if test="${user && user.isAdmin}">
            <div class="nav" role="navigation">
                <ul>
                    <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                    <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </ul>
            </div>
        </g:if>

        <div id="fh5co-product">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="row">
                            <div class="col-md-12">
                                <h2><g:message code="purchase" /></h2>
                            </div>
                            <div class="col-md-12">
                                <label><g:message code="purchase.amount"/>:</label>
                                <span>$${purchase.amount.amount}</span>
                            </div>
                            <div class="col-md-12">
                                <label><g:message code="purchase.date"/>:</label>
                                <span><g:formatDate format="dd-MM-yyyy HH:mm" date="${purchase.date}"/></span>
                            </div>
                            <div class="col-md-12">
                                <label><g:message code="user.label" default="Usuario"/>:</label>
                                <span>${purchase.user.name} ${purchase.user.lastName}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row ">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="credit-card-div">
                            <div class="panel panel-default">
                                <div class="panel-heading">

                                    <div class="row ">
                                        <div class="col-md-12">
                                            <input class="form-control" placeholder="Enter Card Number" type="text">
                                        </div>
                                    </div>

                                    <div class="row ">
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <span class="help-block text-muted small-font"> Expiry</span>
                                        </div>
                                    </div>
                                    <div class="row ">
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <span class="help-block text-muted small-font"> Month</span>
                                            <input class="form-control" placeholder="MM" type="text">
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <span class="help-block text-muted small-font">  Year</span>
                                            <input class="form-control" placeholder="YY" type="text">
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <span class="help-block text-muted small-font">  CCV</span>
                                            <input class="form-control" placeholder="CCV" type="text">
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <asset:image src="cc-card.png" />
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row ">
                                        <div class="col-md-12 pad-adjust">

                                            <input class="form-control" placeholder="Name On The Card" type="text">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 pad-adjust">
                                            <div class="checkbox">
                                                <label>
                                                    <input checked="" class="text-muted" type="checkbox"> Save details for fast payments <a href="#"> learn how ?</a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row ">
                                        <div class="col-md-6 col-sm-6 col-xs-6 pad-adjust">
                                            <g:link class="btn btn-danger btn-outline btn-md" action="show" resource="${purchase}"><g:message code="default.cancel"/></g:link>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-6 pad-adjust">
                                            <g:link class="btn btn-warning btn-outline btn-md" action="validatePay" resource="${purchase}"><g:message code="purchase.pay"/></g:link>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                        <!-- CREDIT CARD DIV END -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    </body>
</html>

grails-app/views/purchase/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'purchase.label', default: 'Purchase')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
    <div id="page">

        <g:if test="${user && user.isAdmin}">
            <div class="nav" role="navigation">
                <ul>
                    <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                    <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </ul>
            </div>
        </g:if>

        <div id="fh5co-product">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="row">
                            <div class="col-md-12">
                                <h2><g:message code="purchase" /></h2>
                            </div>
                            <div class="col-md-12">
                                <label><g:message code="purchase.amount"/>:</label>
                                <span>$${purchase.amount.amount}</span>
                            </div>
                            <div class="col-md-12">
                                <label><g:message code="purchase.date"/>:</label>
                                <span><g:formatDate format="dd-MM-yyyy HH:mm" date="${purchase.date}"/></span>
                            </div>
                            <div class="col-md-12">
                                <label><g:message code="user.label" default="Usuario"/>:</label>
                                <span>${purchase.user.name} ${purchase.user.lastName}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-10 col-md-offset-1">
                        <div id="show-purchase" class="content scaffold-show" role="main">
                            <table class='display'>
                                <tr>
                                    <th><g:message code="cart.image"/></th>
                                    <th><g:message code="cart.name"/></th>
                                    <th><g:message code="cart.description"/></th>
                                    <th><g:message code="cart.price"/></th>
                                </tr>
                                <g:each in="${purchase.products}" var="product">
                                    <tr>
                                        <td>
                                            <asset:image src="products/${product.id}.jpg" height="50" alt="${product.name}" title="${product.name}"/>
                                        </td>
                                        <td>${product.name}</td>
                                        <td>${product.description}</td>
                                        <td>${product.price.amount}</td>
                                    </tr>
                                </g:each>
                            </table>
                            <g:if test="${purchase.isPending()}">
                                <g:link class="btn btn-success btn-outline btn-md" action="pay" resource="${purchase}"><g:message code="purchase.pay"/></g:link>
                            </g:if>

    <g:if test="${user && user.isAdmin}">
                                <g:form resource="${this}" method="DELETE">
                                    <fieldset class="buttons">
                                        <g:link class="edit" action="edit" resource="${this.purchase}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                                        <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                                    </fieldset>
                                </g:form>
                            </g:if>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    </body>
</html>