grails-app/domain/preciosdinamicos/Payment.groovy
package preciosdinamicos

class Payment {
    Purchase purchase

    String paymentMethod
    Date date
    Money amount
    static constraints = {
    }

    static embedded = ['amount']


    Payment(Purchase purchase, String paymentMethod, Money amount) {
        this.purchase = purchase
        this.paymentMethod = paymentMethod
        this.amount = amount
        this.date = new Date()
    }

}

grails-app/controllers/preciosdinamicos/PaymentController.groovy
package preciosdinamicos

class PaymentController {
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index() {}

    def show(Payment payment) {
        respond payment
    }

    def pay() {
        flash.message = "La compra se ha realizado exitosamente"
        redirect getUserFromSession().getCart()
    }

    private User getUserFromSession() {
        def userId = session.getAttribute("user")
        User user = User.findById(userId)
        user
    }
}

grails-app/views/payment/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'payment.label', default: 'Payment')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#create-payment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-payment" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.payment}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.payment}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="payment"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/payment/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'payment.label', default: 'Payment')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-payment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-payment" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.payment}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.payment}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.payment}" method="PUT">
                <g:hiddenField name="version" value="${this.payment?.version}" />
                <fieldset class="form">
                    <f:all bean="payment"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/payment/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'payment.label', default: 'Payment')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#list-payment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-payment" class="content scaffold-list" role="main">
            <h1>Precios Dinámicos</h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${paymentList}" />

            <div class="pagination">
                <g:paginate total="${paymentCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/payment/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'ticket.label', default: 'Ticket')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-ticket" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-ticket" class="content scaffold-show" role="main">
            <h2><g:message code="default.show.label" args="[entityName]" /></h2>
            <f:table collection="${this.ticket.purchase.products}" />
            <g:form resource="${this.ticket}" method="DELETE">
                <fieldset class="buttons">
            <g:link class="create" action="pay" resource="${this.ticket}"><g:message code="default.button.buy.label"
                                                                                           default="buy"/></g:link>
            %{--<g:link class="edit" action="edit" resource="${this.ticket}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
            <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
        --}%</fieldset>
    </g:form>
</div>
</body>
</html>