grails-app/domain/preciosdinamicos/ProductCategory.groovy
package preciosdinamicos

class ProductCategory {
    String name

    ProductCategory(String name) {
        this.name = name
    }

    static constraints = {
        name blank: false, nullable: false
    }

    String toString() {
        this.name
    }
}

grails-app/controllers/preciosdinamicos/ProductCategoryController.groovy
package preciosdinamicos

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ProductCategoryController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ProductCategory.list(params), model: [productCategoryCount: ProductCategory.count()]
    }

    def show(ProductCategory productCategory) {
        User user = User.findById(session["user"])
        if (!user || !user.getIsAdmin()) {
            redirect(controller: "product", action: "index", params: [category: productCategory])
        }
        respond productCategory
    }

    def create() {
        respond new ProductCategory(params)
    }

    @Transactional
    def save(ProductCategory productCategory) {
        if (productCategory == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (productCategory.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond productCategory.errors, view: 'create'
            return
        }

        productCategory.save()

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'productCategory.label', default: 'ProductCategory'), productCategory.id])
                redirect productCategory
            }
            '*' { respond productCategory, [status: CREATED] }
        }
    }

    def edit(ProductCategory productCategory) {
        respond productCategory
    }

    @Transactional
    def update(ProductCategory productCategory) {
        if (productCategory == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (productCategory.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond productCategory.errors, view: 'edit'
            return
        }

        productCategory.save()

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'productCategory.label', default: 'ProductCategory'), productCategory.id])
                redirect productCategory
            }
            '*' { respond productCategory, [status: OK] }
        }
    }

    @Transactional
    def delete(ProductCategory productCategory) {

        if (productCategory == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }
        if (Product.findAll().findAll { it.category == productCategory }.isEmpty()) {
            productCategory.delete()
            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'ProductCategory.label', default: 'ProductCategory'), productCategory.id])
                    redirect action: "index", method: "GET"
                }
                '*' { render status: NO_CONTENT }
            }
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'ProductCategory.label', default: 'ProductCategory'), params.id])
                redirect productCategory
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'ProductCategory.label', default: 'ProductCategory'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/productCategory/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'productCategory.label', default: 'ProductCategory')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#create-productCategory" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index">Ver Lista de Categorías</g:link></li>
            </ul>
        </div>
        <div id="create-productCategory" class="content scaffold-create" role="main">
            <h1>Crear Categoría</h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.productCategory}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.productCategory}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="productCategory"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/productCategory/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'productCategory.label', default: 'ProductCategory')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#edit-productCategory" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-productCategory" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.productCategory}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.productCategory}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.productCategory}" method="PUT">
                <g:hiddenField name="version" value="${this.productCategory?.version}" />
                <fieldset class="form">
                    <f:all bean="productCategory"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/productCategory/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'productCategory.label', default: 'ProductCategory')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#list-productCategory" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create">Agregar Nueva Categoría</g:link></li>
            </ul>
        </div>
        <div id="list-productCategory" class="content scaffold-list" role="main">
            <h1>Precios Dinámicos</h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${productCategoryList}" />

            <div class="pagination">
                <g:paginate total="${productCategoryCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/productCategory/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'productCategory.label', default: 'ProductCategory')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#show-productCategory" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index">Lista de Categorías</g:link></li>
                <li><g:link class="create" action="create">Agregar Nueva Categoría</g:link></li>
            </ul>
        </div>
        <div id="show-productCategory" class="content scaffold-show" role="main">
            <h1>Categoría del Producto</h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="productCategory" />
            <g:form resource="${this.productCategory}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.productCategory}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>