grails-app/domain/preciosdinamicos/ProductVisit.groovy
package preciosdinamicos


class ProductVisit {
    User user
    Product product
    Integer day
    Integer count

    ProductVisit(User user, Product product, Integer day, Integer count) {
        this.user = user
        this.product = product
        this.day = day
        this.count = count
    }

    void increaseVisit() {
        this.count = this.count ?: 0
        this.count++
        this.save()
    }
    static constraints = {
        user nullable: false
        product nullable: false
    }

    String toString() {
        "User: " + this.user +
                "\n Product: " + this.product +
                "\n day: " + this.day +
                "\n count: " + this.count
    }
}

grails-app/controllers/preciosdinamicos/ProductVisitController.groovy
package preciosdinamicos

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ProductVisitController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ProductVisit.list(params), model:[productVisitCount: ProductVisit.count()]
    }

    def show(ProductVisit productVisit) {
        respond productVisit
    }

    def create() {
        respond new ProductVisit(params)
    }

    @Transactional
    def save(ProductVisit productVisit) {
        if (productVisit == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (productVisit.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond productVisit.errors, view:'create'
            return
        }

        productVisit.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'productVisit.label', default: 'ProductVisit'), productVisit.id])
                redirect productVisit
            }
            '*' { respond productVisit, [status: CREATED] }
        }
    }

    def edit(ProductVisit productVisit) {
        respond productVisit
    }

    @Transactional
    def update(ProductVisit productVisit) {
        if (productVisit == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (productVisit.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond productVisit.errors, view:'edit'
            return
        }

        productVisit.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'productVisit.label', default: 'ProductVisit'), productVisit.id])
                redirect productVisit
            }
            '*'{ respond productVisit, [status: OK] }
        }
    }

    @Transactional
    def delete(ProductVisit productVisit) {

        if (productVisit == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        productVisit.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'productVisit.label', default: 'ProductVisit'), productVisit.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'productVisit.label', default: 'ProductVisit'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/productVisit/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'productVisit.label', default: 'ProductVisit')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#create-productVisit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-productVisit" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.productVisit}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.productVisit}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="productVisit"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/productVisit/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'productVisit.label', default: 'ProductVisit')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#edit-productVisit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-productVisit" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.productVisit}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.productVisit}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.productVisit}" method="PUT">
                <g:hiddenField name="version" value="${this.productVisit?.version}" />
                <fieldset class="form">
                    <f:all bean="productVisit"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/productVisit/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'productVisit.label', default: 'ProductVisit')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#list-productVisit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-productVisit" class="content scaffold-list" role="main">
            <h1>Precios Dinámicos</h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${productVisitList}" />

            <div class="pagination">
                <g:paginate total="${productVisitCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/productVisit/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'productVisit.label', default: 'ProductVisit')}" />
        <title>Precios Dinámicos</title>
    </head>
    <body>
        <a href="#show-productVisit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-productVisit" class="content scaffold-show" role="main">
            <h1>Producto</h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="productVisit" />
            <g:form resource="${this.productVisit}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.productVisit}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>